# Start with the .NET Core SDK image
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env

# Copy the project file and restore dependencies
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore

# Copy the remaining source code and build the app
COPY . ./
RUN dotnet publish -c Release -o out

# Build the runtime image
FROM mcr.microsoft.com/dotnet/runtime:5.0
WORKDIR /app
COPY --from=build-env /app/out .

# Set environment variables
ENV Amount=10
ENV Threads=1

# Expose the port used by the app
EXPOSE 80

# Start the app
ENTRYPOINT ["dotnet", "scrapper.dll"]